### ISSUE TITLE
Cadical parameters used in the experiments?

### ISSUE THREAD

**Issue by wu-haoze** [bsubercaseaux/PackingChromaticTacas#1]
Hi! Thanks for this very cool work. I hope to reproduce the runtime results of the paper and am wondering whether I should use the default CaDiCaL configuration when performing the experiment. Incidentally, did you find/use non-default hyper-parameter settings that can improve runtime performance?

Thanks in advance!

**Comment by bsubercaseaux** [comment]
Hi! For the best possible results we used a modified version of CaDiCaL (by my advisor Marijn Heule), that turned out to be slightly faster than Kissat. I would try both Kissat and CaDiCaL with default parameters. I remember in certain experiments using ``--unsat'' improved performance, while it lowered it in others. Similarly, I think ``--forcephase'' was sometimes helpful. Nevertheless, I believe that unless stated otherwise, all experiments reported used default parameters. If there's any particular datapoint in which you don't get a runtime similar to the paper, please let me know and I will be happy to take a look.

**Comment by wu-haoze** [comment]
Thanks a lot!
